### ISSUE TITLE
Question of reproducing the results

### ISSUE THREAD

**Issue by bruno686** [Jinfeng-Xu/MENTOR#2]
Hello, the result of Mentor after running on 
baby is, Test: recall@10: 0.0652 recall@20: 0.1038 ndcg@10: 0.0350 ndcg@20: 0.0450; 
sports is, Test: recall@10: 0.0737 recall@20: 0.1122 ndcg@10: 0.04 ndcg@20: 0.0499.
There is difference with the paper' result, may I ask what are the hyperparameter settings of the paper's result on each dataset?

Best regards,

**Comment by Jinfeng-Xu** [comment]
Hi Bruno

Thanks for your interest.
The results about MENTOR are not absolutely stable; for example, in recall@20, the results of MENTOR are variable from 0.1032-0.1054 in the 20 sets of experiments I recorded. But for the results mentioned in the paper, our improvement is statistically significant where the p-value is less than 0.05. 
BTW, we will release the experimental record and the checkpoint of the optimal model after the paper is officially accepted by the conference. Thanks again for your interest. 

Best,
Jinfeng

**Comment by Jinfeng-Xu** [comment]
> Hello, the result of Mentor after running on baby is, Test: recall@10: 0.0652 recall@20: 0.1038 ndcg@10: 0.0350 ndcg@20: 0.0450; sports is, Test: recall@10: 0.0737 recall@20: 0.1122 ndcg@10: 0.04 ndcg@20: 0.0499. There is difference with the paper' result, may I ask what are the hyperparameter settings of the paper's result on each dataset?
> 
> Best regards,

Hi Bruno

Thanks for your interest.
The results about MENTOR are not absolutely stable; for example, in recall@20, the results of MENTOR are variable from 0.1032-0.1054 in the 20 sets of experiments I recorded. But for the results mentioned in the paper, our improvement is statistically significant where the p-value is less than 0.05.
BTW, we will release the experimental record and the checkpoint of the optimal model after the paper is officially accepted by the conference. Thanks again for your interest.

Best,
Jinfeng

**Comment by liupanxing** [comment]
> Hello, the result of Mentor after running on您好，Mentor 在运行后的结果是 baby is, Test: recall@10: 0.0652 recall@20: 0.1038 ndcg@10: 0.0350 ndcg@20: 0.0450;对于婴儿类：测试指标 recall@10: 0.0652，recall@20: 0.1038，ndcg@10: 0.0350，ndcg@20: 0.0450； sports is, Test: recall@10: 0.0737 recall@20: 0.1122 ndcg@10: 0.04 ndcg@20: 0.0499.对于体育类：测试指标 recall@10: 0.0737，recall@20: 0.1122，ndcg@10: 0.04，ndcg@20: 0.0499。 There is difference with the paper' result, may I ask what are the hyperparameter settings of the paper's result on each dataset?论文的结果与我们的结果存在差异，想请问论文在各个数据集上的超参数设置分别是多少？
> 
> Best regards,祝好，

Hi @bruno686,

Thanks for sharing your insights here! I am currently working on my master's thesis focusing on multimodal recommendation, and I am trying to use MENTOR as a baseline.

I saw that you successfully ran the model and got a recall@20 of 0.1038 on Baby and 0.1122 on Sports. I am also trying to run the Clothing dataset. Could you kindly share the exact hyperparameter settings (e.g., seed, knn_k, align_weight) you used for these datasets?

If you could share your .yaml configuration files for Baby, Sports, and Clothing, it would save me a lot of time in my current experiments. Thank you in advance for your help!
